### ISSUE TITLE
Crates don't get visually unloaded

### ISSUE THREAD

**Issue by LFalch** [tibyte/ludum34#1]
When pressing unload, no crate disappears.

**Comment by mtib** [comment]
Fix that you stupid, lazy, lovely GIT!!

**Comment by LFalch** [comment]
Okay, I will fix it!

**Comment by LFalch** [comment]
This is impossible to fix!

**Comment by mtib** [comment]
Still an Issue!

**Comment by LFalch** [comment]
ISSUE HAS BEEN FIXED!
