### ISSUE TITLE
tracking scores

### ISSUE THREAD

**Issue by mtib** [tibyte/ludum34#2]
I figured that the scores currently don't say much, as long as we don't save the version of the game with them... So we know how "hard" it was to get the points.
That's something that I am happily willing to let you, @LFalch, do that.

Meanwhile, I'll use some of my time to code up the leaderboard

**Comment by LFalch** [comment]
I'll see when Christmas isn't eating my time.

**Comment by mtib** [comment]
Oh, yeah...
I kinda forgot about Christmas, 
Sorry to bother you, enjoy your family-time! :christmas_tree:
